### ISSUE TITLE
Implement support for multi-tenant Kafka Source

### ISSUE THREAD

**Issue by zroubalik** [knative-sandbox/eventing-autoscaler-keda#26]
https://docs.google.com/document/d/1jARXfiD4YrAbLQCMo0GJc2tA6CscDpwZvZKEeccjujM/edit#heading=h.n8a530nnrb

**Comment by lionelvillard** [comment]
The current autoscaler implementation is tightly coupled with the KafkaSource controller implementation, for instance it knows a Deployment is created for each KafkaSource instances and that the name of these deployments follow a certain pattern. That's obviously won't work for MT KafkaSource implementations, or implementations that don't use deployments.

So the first step is to decoupled these two implementations by leveraging KEDA CRD support. I'm proposing the following changes:
1.  Change the ScaledObject generated by the autoscaler to target KafkaSources instead of the deployments
2. Change the KafkaSource controller to watch for `spec.replicas` changes and update the underlying implementation accordingly. In the single-tenant case, this means changing the number of replicas in the Deployment

@zroubalik How does that sound to you? Am I missing something?

**Comment by zroubalik** [comment]
@lionelvillard yeah, that's the way I'd like the controller go forward, ie. target directly the resources and those resources can then react to the scaling appropriately.

I'd correct point 2. - the correct way is, that the Kafka Source is gonna define `/scale` subresource, which will KEDA target (not directly the `spec.replicas`).

**Comment by lionelvillard** [comment]
yes I took a shortcut with point 2. `/scale` subresource points to `spec.replicas`.
